### ISSUE TITLE
(Spring Security) Input sanitation and validation

### ISSUE THREAD

**Issue by drageset** [statisticsnorway/klass-subsets-api#13]
Inputs need to be validated (are they in the format and range we expect?) and sanitized (are we sure they do not contain some code that will be executed somewhere else?).

date and version strings are validated by a strict regex, and that validation will stop any code from getting through. By "id"s are not validated or cleaned. And maybe not subset jsons before posting/putting either.

**Comment by alina-lapina** [comment]
Input validation we will define while developing, I'll express my vision in separate issues, 
The main idea is that 
- some subset values are not allowed, and 
- some combination of values in different fields are not allowed, as well as 
- some actions with some values are not allowed based on its previous state or state of other subset fields. 
- in addition, some values will be influenced by changes done in other fields.
