### ISSUE TITLE
make sure subsets are not overwritten, but instead a new version is submitted

### ISSUE THREAD

**Issue by drageset** [statisticsnorway/klass-subsets-api#16]
If version 1.0.0 already exists and is already published, it should not be possible to overwrite it /change its codes, right? So when a "PUT" operation is made on a subset, the subset that is submitted must have a new version number. That would make sense to me at least. But in the case where a given version is NOT published, it should be possible to submit an update of that version.

**Comment by alina-lapina** [comment]
@drageset could you elaborate on this issue, please

**Comment by drageset** [comment]
@alina-lapina I've elaborated the description. Do you know what I mean, and is it correct?
