### ISSUE TITLE
API Guide

### ISSUE THREAD

**Issue by alina-lapina** [statisticsnorway/klass-subsets-api#17]
**Is your feature request related to a problem? Please describe.**
Developers and users have to have exhaustive API documentation at any point in time.

**Describe the solution you'd like**
Suggest to use AsciiDoc Maven plugin (check out the implementation for Klass API project https://github.com/statisticsnorway/klass)

**Describe alternatives you've considered**
I'm open to any other automated API doc generators.

**Comment by runejo** [comment]
This is now a UserStory in Jira https://jira.ssb.no/browse/KF-346
