### ISSUE TITLE
length limit on subset IDs?

### ISSUE THREAD

**Issue by drageset** [statisticsnorway/klass-subsets-api#21]
Should IDs have a length limit? (Yes, most likely)

What should that limit be? (should be medium-long to allow full names? Should be not that long so it can be displayed easily? in a certain place)

**Comment by alina-lapina** [comment]
Does LDS has any limitations?

**Comment by drageset** [comment]
> 
> 
> Does LDS has any limitations?

According to Kim: It's just a regular String, so not really.
