### ISSUE TITLE
Badly formed error responses

### ISSUE THREAD

**Issue by alina-lapina** [statisticsnorway/klass-subsets-api#36]
**Describe the bug**
Error responses are not triggered/caught on the client-side. (fetch-try-catch), 

**To Reproduce**
1. implement standard fetch-try-catch on a website:
```
const fetchData = async () => {
            try {
                const response = await fetch(`${subsetsServiceEndpointAUTH}${path}`, {
                    method: 'POST',
                    headers: { 'Content-Type': 'application/json' },
                    body: JSON.stringify(payload),
                });
                let json = await response.json();
                console.log('SUCCESS', json)
            }
            catch (e) {
                console.log('ERROR ', e.message);
                alert(e.message);
            }
        };
```
(or use subsets-client v0.4)
2. try to POST an update to cause an error:
`POST {subsets-service-endpoint}/v1/subsets/ `
3. Run the code, and check the console. The catch-part is not fired.

**Expected behavior**
When server responses with en HTTPStatus other then OK (2XX), it should throw en exception with an error message, not regular response.

**Screenshots**
![image](https://user-images.githubusercontent.com/21969896/85234629-09ca8d80-b40f-11ea-9917-8b1018594cef.png)

**Additional context**

- https://www.baeldung.com/exception-handling-for-rest-with-spring
- https://www.springboottutorial.com/spring-boot-exception-handling-for-rest-services
- https://www.baeldung.com/global-error-handler-in-a-spring-rest-api
- https://blog.jayway.com/2014/10/19/spring-boot-error-responses/
- https://stackoverflow.com/questions/26236811/spring-boot-customize-http-error-response

**Comment by drageset** [comment]
I still don't understand the problem completely. Isn't a non-200 status code the HTTP way of throwing an exception from the API to the client? Are not the articles you are linking to only about implementation details for how to return a 4XX code properly in the spring boot way?

If you want to handle non 200's in your fetch-try-catch block, isn't that your job on the client side?

Like so: https://learnwithparam.com/blog/how-to-handle-fetch-errors/

**Comment by alina-lapina** [comment]
@drageset You was right, I just remember it worked on a previous project. 
I've found out it worked because of the empty (lame) server response, which caused an internal javascript error, which was caught in `fetch()`. 
Thank you for the awareness!
