### ISSUE TITLE
Only whitelisted key-values can be processed and stored

### ISSUE THREAD

**Issue by alina-lapina** [statisticsnorway/klass-subsets-api#74]
**Describe the bug**
When the server gets a message with subset details, it stores everything it gets. 

**To Reproduce**
https://subsets-service.staging-bip-app.ssb.no/v1/subsets/uttrekk_for_test_i_sommer/versions

**Expected behavior**
Only fields named in ClassificationSubset schema could be processed and/or stored. It is efficient and safe. 
A possible attack vector: An adversary may store a script as a non-defined field, which is not sanitized, and then make a client run the script. 

**Screenshots**
![image](https://user-images.githubusercontent.com/21969896/89130914-5a063680-d509-11ea-8a8a-6cbdb4363cbe.png)

**Comment by drageset** [comment]
The only thing that appears to not adhere to the schema is the content of an entry in the array Codes. A Code should only have two fields, namely a ranking and an URN. But in this case it has more fields.

**Comment by drageset** [comment]
versionValidUntil does not appear in any version when you go to that URL (https://subsets-service.staging-bip-app.ssb.no/v1/subsets/uttrekk_for_test_i_sommer/versions) at this time.

**Comment by drageset** [comment]
> It should not be possible to push into the system anything but legitimate fields and values!

I agree, and as far as I understand this is part of the responsibility of LDS. We might not be using it right. We should clear this up with Kim, before we implement anything, maybe?

**Comment by alina-lapina** [comment]
> > It should not be possible to push into the system anything but legitimate fields and values!
> 
> I agree, and as far as I understand this is part of the responsibility of LDS. We might not be using it right. We should clear this up with Kim, before we implement anything, maybe?

Agree
